name: COMPAS compile test

on:
  workflow_dispatch: # allow manual triggering of this workflow
  push:
    paths: ['src/**', "compas_python_utils/**"] # only changes to src/ compas_python_utils/ will trigger this workflow
  pull_request:
    branches:
      - dev

jobs:
  compas:
    name: Build COMPAS
    runs-on: ${{ matrix.os}}
    container: ${{matrix.container}}  # to run the job on centos 7 docker image which runs on ubuntu-18.04 machine
    strategy:
      fail-fast: false  #in case build failed on one of the runners, it won't stop building on other runners
      matrix:
        os: [ubuntu-20.04]  # virtual machines to run the job
        # REPLACE WITH BELOW FOR OTHER OS
        # os: [ubuntu-20.04, ubuntu-18.04, macos-11]
        # include: # add the combination to run the centos container only on ubuntu-18.04
        #   - os: ubuntu-18.04
        #     container: 'centos:7'
    steps:
      - uses: actions/checkout@v2

      # This step will run only on ubuntu-20.04 (ADD OTHER OS IF NEEDED)
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu-20') 
        run: |
          cd misc/cicd-scripts
          chmod 755 linux-dependencies
          ./linux-dependencies

      - name: Build Compas
        run: |
          cd src && make -j $(nproc) -f Makefile
          ./COMPAS -v

      - name: Run Compas and test python post-processing scripts
        run: |
          python3 -m pip install .
          export COMPAS_ROOT_DIR=${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/misc/examples/methods_paper_plots/detailed_evolution   
          echo "Run example COMPAS job"
          python3 runSubmitDemo.py  
          echo "Testing COMPAS python post-processing scripts"
          cd ${GITHUB_WORKSPACE}
          pytest py_tests/