name: COMPAS compile test

on:
  workflow_dispatch: # allow manual triggering of this workflow
  push:
    paths: ['src/**', "compas_python_utils/**"] # only changes to src/ compas_python_utils/ will trigger this workflow
  pull_request:
    branches:
      - dev

jobs:
  compas:
    name: Build COMPAS
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies 
        run: sudo apt-get update; sudo apt install g++ libboost-all-dev libgsl-dev libhdf5-serial-dev 

      - name: Build COMPAS
        run: cd src && make -j $(nproc) -f Makefile

      - name: Run Compas and test python post-processing scripts
        run: |
          pip install .
          export COMPAS_ROOT_DIR=${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/misc/examples/methods_paper_plots/detailed_evolution
          python3 runSubmitDemo.py
          cd ${GITHUB_WORKSPACE}
          pytest py_tests/
