name: COMPAS compile test

on:
  workflow_dispatch: # allow manual triggering of this workflow
  push:
    paths: ['src/**', "compas_python_utils/**"] # only changes to src/ compas_python_utils/ will trigger this workflow
  pull_request:
    branches:
      - dev

jobs:
  compas:
    name: Build COMPAS
    runs-on: ${{ matrix.os}}
    container: ${{matrix.container}}  # to run the job on centos 7 docker image which runs on ubuntu-18.04 machine
    strategy:
      fail-fast: false  #in case build failed on one of the runners, it won't stop building on other runners
      matrix:
        os: [ubuntu-20.04]  # virtual machines to run the job
        # REPLACE WITH BELOW FOR OTHER OS
        # os: [ubuntu-20.04, ubuntu-18.04, macos-11]
        # include: # add the combination to run the centos container only on ubuntu-18.04
        #   - os: ubuntu-18.04
        #     container: 'centos:7'
    steps:
      - uses: actions/checkout@v2

      # This step will run only on ubuntu-20.04 (ADD OTHER OS IF NEEDED)
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu-20')
        run: |
          cd misc/cicd-scripts
          chmod 755 linux-dependencies
          ./linux-dependencies

      - name: Build Compas
        run: |
          cd src && make -j $(nproc) -f Makefile
          ./COMPAS -v

      - name: Run example COMPAS job
        run: |
          python3 -m pip install -e .[dev]
          export COMPAS_ROOT_DIR=${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/misc/examples/methods_paper_plots/detailed_evolution
          chmod 755 run.sh
          ./run.sh
        continue-on-error: true # continue even if this job fails

      - name: Run pytests
        # Run tests and collect coverage data
        run: |
          cd ${GITHUB_WORKSPACE}
          export COMPAS_ROOT_DIR=${GITHUB_WORKSPACE}
          pytest --cov=compas_python_utils/ py_tests/
          coverage html
          coverage-badge -o coverage_badge.svg -f

      - name: Archive run artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            htmlcov/
            coverage_badge.svg
            ${GITHUB_WORKSPACE}/py_tests/test_artifacts/
