name: COMPAS compile test

on:
  workflow_dispatch: # allow manual triggering of this workflow
  push:
    paths: ['src/**', "compas_python_utils/**"] # only changes to src/ compas_python_utils/ will trigger this workflow
  pull_request:
    branches:
      - dev

jobs:
  compas:
    name: Build COMPAS
    runs-on: ${{ matrix.os}}
    container: ${{matrix.container}}  # to run the job on centos 7 docker image which runs on ubuntu-18.04 machine
    strategy:
      fail-fast: false  #in case build failed on one of the runners, it won't stop building on other runners
      matrix:
        os: [ubuntu-20.04]  # runners(virtual machines) to run the job on
        # include: # add the combination to run the centos container only on ubuntu-18.04
        #   - os: ubuntu-18.04
        #     container: 'centos:7'

    steps:
      - uses: actions/checkout@v2

#      - name: Install dependencies 
#        run: |
#          sudo apt-get update
#          sudo apt install texlive-latex-extra cm-super dvipng
#          sudo apt update && sudo apt install g++ libboost-all-dev libgsl-dev libhdf5-serial-dev 
#          sudo apt-get install gcc libpq-dev -y
#          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
#
#      - name: Build COMPAS
#        run: cd src && make -j $(nproc) -f Makefile
#
#      - name: Run Compas and test python post-processing scripts
#        run: |
#          pip install .
#          export COMPAS_ROOT_DIR=${GITHUB_WORKSPACE}
#          cd ${GITHUB_WORKSPACE}/misc/examples/methods_paper_plots/detailed_evolution
#          python3 runSubmitDemo.py
#          cd ${GITHUB_WORKSPACE}
#          pytest py_tests/

      # This step will run only on ubuntu-20.04
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu-20') 
        run: |
          cd misc/cicd-scripts
          chmod 755 linux-dependencies
          ./linux-dependencies
      # This step will run only on centos 7 container on ubuntu-18.04
      - name: Install dependencies on centos docker container
        if: startsWith(matrix.container, 'centos')
        run: |
          cd misc/cicd-scripts
          chmod 755 centos-dependencies
          ./centos-dependencies
      
      # This step will run only on macos
      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          cd misc/cicd-scripts
          chmod 755 macos-dependencies
          ./macos-dependencies
      # This step will run only on all runners
      # **To be investgated further** COMPAS doesn't build on Centos
      - name: Build Compas
        run: |
          cd src && make -j $(nproc) -f Makefile
          ./COMPAS -v
        env:
          nproc: 4

      # This step will run only on all runners
      - name: Install Python packages
        run: |
          python3 -m pip install -r requirements.txt
      # This step will run on all runners
      # **To be investigated further** plotting script is currently failing on macos because 
      # for some reason it cannot recognise latex is installed
      - name: Run Post-Processing Python Scripts
        if: startsWith(matrix.os, 'ubuntu-20') || startsWith(matrix.os, 'ubuntu-18')
        run: |
          cd misc/cicd-scripts
          chmod 755 python-scripts
          ./python-scripts
      - name: run python scripts on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install basictex
          brew install texlive
          eval "$(/usr/libexec/path_helper)"
          export PATH="/usr/local/texlive:/Library/TeX/texbin:$PATH"
          sudo tlmgr update --self
          sudo tlmgr install dvipng
          sudo tlmgr install texliveonfly
          sudo tlmgr install environ
          sudo tlmgr install adjustbox
          sudo tlmgr install tcolorbox
          sudo tlmgr install collectbox
          sudo tlmgr install ucs
          sudo tlmgr install trimspaces
          sudo tlmgr install titling
          sudo tlmgr install enumitem
          sudo tlmgr install rsfs
          eval "$(/usr/libexec/path_helper)"
          export COMPAS_ROOT_DIR=${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/misc/examples/methods_paper_plots/detailed_evolution
          python3 runSubmitDemo.py
          python3 plot_detailed_evolution.py
