name: COMPAS compile test

on: push

jobs:
  compas:
    name: Build COMPAS
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies 
        run: sudo apt-get update; sudo apt install g++ libboost-all-dev libgsl-dev libhdf5-serial-dev 

      - name: Build COMPAS
        run: cd src && make -j $(nproc) -f Makefile

      - name: Run example BBH
        run: |
          pip install -r requirements.txt
          cd ci_tests/
          chmod 755 methods_paper_bbh.sh
          ./methods_paper_bbh.sh
