name: COMPAS compile test

on:
  workflow_dispatch: # allow manual triggering of this workflow
  pull_request:
    branches:
      - dev
    paths: ['src/**', "compas_python_utils/**", "py_tests/**", ".github/workflows/**"]

jobs:
  compas:
    name: Build COMPAS
    runs-on: ${{ matrix.os}}
    container: ${{matrix.container}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu-20')
        run: |
          cd misc/cicd-scripts
          chmod 755 linux-dependencies
          ./linux-dependencies

      - name: Build Compas
        run: |
          cd src && make -j $(nproc) -f Makefile
          ./COMPAS -v

      - name: Run example COMPAS job
        run: |
          python3 -m pip install -e .[dev]
          export COMPAS_ROOT_DIR=${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/misc/examples/methods_paper_plots/detailed_evolution
          chmod 755 run.sh
          cat run.sh
          ./run.sh

      - name: Run pytests
        # Run tests and collect coverage data
        run: |
          cd ${GITHUB_WORKSPACE}
          export COMPAS_ROOT_DIR=${GITHUB_WORKSPACE}
          pytest --cov=compas_python_utils/ py_tests/
          coverage html
          coverage-badge -o coverage_badge.svg -f

      - name: Archive run artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            htmlcov/
            coverage_badge.svg
            ${GITHUB_WORKSPACE}/py_tests/test_artifacts/
