name: COMPAS Compile CI

on:
  pull_request:
      branches: [ dev ]
  push: # testing

jobs:
  compile:
    name: Build Docker image and push to DockerHub
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build Compas
        run: cd src && make -j $(nproc) -f Makefile
